### ISSUE TITLE
复制进去的时候出了问题

### ISSUE THREAD

**Issue by Chefback** [axiaoxin/vim-settings#3]
Error detected while processing /home/chefback/.vimrc:
line   15:
E117: Unknown function: vundle#begin
line   20:
E492: Not an editor command: Plugin 'gmarik/Vundle.vim'
line   26:
E492: Not an editor command: Plugin 'kabbamine/vcoolor.vim'
line   27:
E492: Not an editor command: Plugin 'guns/vim-clojure-highlight'
line   28:
E492: Not an editor command: Plugin 'guns/vim-sexp'
line   29:
E492: Not an editor command: Plugin 'guns/vim-clojure-static'
line   30:
E492: Not an editor command: Plugin 'tpope/vim-fireplace'
line   31:
E492: Not an editor command: Plugin 'kien/rainbow_parentheses.vim'
line   32:
E492: Not an editor command: Plugin 'mattn/emmet-vim'
line   33:
E492: Not an editor command: Plugin 'dhruvasagar/vim-table-mode'
line   34:
E492: Not an editor command: Plugin 'gorodinskiy/vim-coloresque'
line   35:
E492: Not an editor command: Plugin 'jelera/vim-javascript-syntax'
line   36:
E492: Not an editor command: Plugin 'walm/jshint.vim'
line   37:
E492: Not an editor command: Plugin 'moll/vim-node'
line   38:
E492: Not an editor command: Plugin 'airblade/vim-gitgutter'
line   39:
E492: Not an editor command: Plugin 'Yggdroot/indentLine'
line   40:
E492: Not an editor command: Plugin 'nvie/vim-flake8'
line   46:
E492: Not an editor command: Plugin 'axiaoxin/favorite-vim-colorscheme'
line   47:
E492: Not an editor command: Plugin 'junegunn/vim-emoji'
line   48:
E492: Not an editor command: Plugin 'mhinz/vim-startify'
line   49:
E492: Not an editor command: Plugin 'terryma/vim-multiple-cursors'
line   50:
E492: Not an editor command: Plugin 'suan/vim-instant-markdown'
line   51:
E492: Not an editor command: Plugin 'tpope/vim-surround'
line   52:
E492: Not an editor command: Plugin 'honza/vim-snippets'
line   53:
E492: Not an editor command: Plugin 'bling/vim-airline'
line   54:
E492: Not an editor command: Plugin 'kien/ctrlp.vim'
line   55:
E492: Not an editor command: Plugin 'majutsushi/tagbar'
line   56:
E492: Not an editor command: Plugin 'scrooloose/nerdcommenter'
line   57:
E492: Not an editor command: Plugin 'scrooloose/nerdtree'
line   59:
E117: Unknown function: vundle#end
line  118:
E185: Cannot find color scheme 'Tomorrow-Night-Bright'
``

**Comment by crazydogen** [comment]
Try to switch to root
`sudo -s`
`cd~`  
`vim .vimrc`
and then `：PluginInstall`
